#Build Stage
FROM maven:eclipse-temurin AS build
COPY . .
RUN mvn clean package -Dmaven.test.skip

#Launch Stage
FROM adoptopenjdk/openjdk11:alpine
RUN mkdir /springboot-app
WORKDIR /springboot-app
ARG FILE_JAR=target/*.jar
COPY --from=build ${FILE_JAR} /springboot-app/app.jar
ENTRYPOINT ["java", "-jar"]
CMD ["/springboot-app/app.jar"]
